# version: '3.8'

services:
  backend:
    depends_on:
      - mongo
    image: backend
    build: './backend'
    environment:
      NODE_ENV: production
      DB: mongodb+srv://android21:secret07@cluster0.meamgnu.mongodb.net/gallium31?retryWrites=true&w=majority&appName=Cluster0
      PORT: "8080"
      SECRET_KEY: sikretNaMalupit 
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend:
    depends_on:
      - backend
    image: frontend
    build: './frontend'
    env_file:  
      - ./frontend/.env 
    ports:
      - "3000:3000"
    networks:
      - my-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:



